package com.pu.dao;

import com.pu.domain.ItemStock;
import org.apache.ibatis.annotations.Param;

public interface ItemStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Mar 26 11:10:15 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Mar 26 11:10:15 CST 2020
     */
    int insert(ItemStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Mar 26 11:10:15 CST 2020
     */
    int insertSelective(ItemStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Mar 26 11:10:15 CST 2020
     */
    ItemStock selectByPrimaryKey(Integer id);
    ItemStock selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Mar 26 11:10:15 CST 2020
     */
    int updateByPrimaryKeySelective(ItemStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Mar 26 11:10:15 CST 2020
     */
    int updateByPrimaryKey(ItemStock record);

    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);
}