package com.pu.dao;

import com.pu.domain.StockLog;

public interface StockLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri Apr 03 17:03:02 CST 2020
     */
    int deleteByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri Apr 03 17:03:02 CST 2020
     */
    int insert(StockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri Apr 03 17:03:02 CST 2020
     */
    int insertSelective(StockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri Apr 03 17:03:02 CST 2020
     */
    StockLog selectByPrimaryKey(String stockLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri Apr 03 17:03:02 CST 2020
     */
    int updateByPrimaryKeySelective(StockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_log
     *
     * @mbg.generated Fri Apr 03 17:03:02 CST 2020
     */
    int updateByPrimaryKey(StockLog record);
}